ALTER TABLE Student ALTER COLUMN birthday DATE NOT NULL;
ALTER TABLE Mark ALTER COLUMN student_id BIGINT NOT NULL;
ALTER TABLE Mark ALTER COLUMN subject_id BIGINT NOT NULL;
ALTER TABLE Mark ADD CONSTRAINT mark CHECK (mark BETWEEN 1 AND 10);
ALTER TABLE Subject ADD CONSTRAINT grade CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE PaymentType ALTER COLUMN name VARCHAR(25) UNIQUE;
ALTER TABLE Payment ALTER COLUMN type_id bigint NOT NULL;
ALTER TABLE Payment ALTER COLUMN amount DECIMAL NOT NULL;
ALTER TABLE Payment ALTER COLUMN payment_date DATETIME NOT NULL;


